// <auto-generated />
namespace ASP220214V4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_custom_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_custom_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202202141714288_update_custom_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
